# Generated by Django 6.0.5 on 2026-07-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_content_alter_note_id_alter_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
