# Generated by Django 5.2.1 on 2026-05-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notes", "0002_alter_note_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(default=True)),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.note"
                    ),
                ),
            ],
        ),
    ]
